# -*- coding: utf-8 -*-
"""MMS-Projekat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LaxelTOI_xyGA1_pb4_c6mR_3AZDlKeG
"""

!pip install -q condacolab
import condacolab
condacolab.install()

# Commented out IPython magic to ensure Python compatibility.
# Clone the repository
!git clone https://github.com/JeremyIV/diffc.git
# %cd diffc

# Install dependencies into the default conda environment
!conda env update -n base -f environment.yml

# Install the Hugging Face datasets library
!pip install datasets huggingface_hub

import os
from tqdm import tqdm
from datasets import load_dataset
from huggingface_hub import login

# Authenticate with Hugging Face
HF_TOKEN = "HF_TOKEN"  # Paste your token here
login(token=HF_TOKEN)

# Stream validation split
dataset = load_dataset("ILSVRC/imagenet-1k", split="validation", streaming=True)

# Define the target directory inside the cloned repo structure
output_dir = "data/imagenet_subset"
os.makedirs(output_dir, exist_ok=True)

print("Streaming and saving 100 validation images...")
count = 0
max_images = 100

for item in tqdm(dataset, total=max_images):
    img = item['image'].convert('RGB')
    img.save(os.path.join(output_dir, f"img_{count:04d}.png"))
    count += 1
    if count >= max_images:
        break

print(f"Successfully saved {count} images to {output_dir}")

!conda run -n base pip install pillow torchvision datasets diffusers transformers accelerate torch scipy

!conda run -n base pip install cupy-cuda12x omegaconf einops lpips piq

# Install rust/cargo via conda and maturin via pip in base
!conda install -n base -y -c conda-forge rust
!conda run -n base pip install maturin

import os
import subprocess

# Search for the zipf_encoding folder containing Cargo.toml
target_dir = None
for root, dirs, files in os.walk("/content/diffc"):
    if "Cargo.toml" in files:
        with open(os.path.join(root, "Cargo.toml"), "r") as f:
            if "zipf" in f.read():
                target_dir = root
                break

if target_dir:
    print(f"Found zipf_encoding directory at: {target_dir}")
    print("Compiling and installing the Rust extension...")
    # Compile the extension inside the base environment
    result = subprocess.run(
        ["conda", "run", "-n", "base", "pip", "install", target_dir],
        capture_output=True,
        text=True
    )
    if result.returncode == 0:
        print("Success: Compilation and installation completed!")
    else:
        print("Compilation failed. Error output below:")
        print(result.stderr)
else:
    print("Could not locate a Cargo.toml for zipf_encoding. Current directory structure:")
    # Fallback to list files if the search fails
    !find /content/diffc -name "*zipf*"

!conda run -n base pip install easydict scikit-image imageio matplotlib

import os
import shutil

# Paths to check
src_path = "/content/data/imagenet_subset"
dst_path = "/content/diffc/data/imagenet_subset"

# Count images in each folder
src_count = len(os.listdir(src_path)) if os.path.exists(src_path) else 0
dst_count = len(os.listdir(dst_path)) if os.path.exists(dst_path) else 0

print(f"Images found in default Colab directory: {src_count}")
print(f"Images found in repository directory: {dst_count}")

# If they are in the wrong place, move them automatically
if src_count > 0:
    os.makedirs(dst_path, exist_ok=True)
    for filename in os.listdir(src_path):
        shutil.move(os.path.join(src_path, filename), os.path.join(dst_path, filename))
    print(f"\nMoved {src_count} images to the repository directory: {dst_path}")
elif dst_count > 0:
    print("\nImages are already in the correct directory.")
else:
    print("\nNo images were found in either folder. Please check if your Hugging Face download step ran successfully.")

import os
from PIL import Image

image_dir = "/content/diffc/data/imagenet_subset"
files = [f for f in os.listdir(image_dir) if f.endswith(".png")]

print(f"Resizing {len(files)} images to 512x512...")
for f in files:
    path = os.path.join(image_dir, f)
    img = Image.open(path).convert("RGB")

    # Crop to square (center crop)
    width, height = img.size
    min_dim = min(width, height)
    left = (width - min_dim) / 2
    top = (height - min_dim) / 2
    right = (width + min_dim) / 2
    bottom = (height + min_dim) / 2
    img_cropped = img.crop((left, top, right, bottom))

    # Resize to 512x512
    img_resized = img_cropped.resize((512, 512), Image.Resampling.LANCZOS)
    img_resized.save(path)

print("Preprocessing complete! All images are now standard 512x512.")

!rm -rf /content/diffc/results/SD-1.5-base/imagenet_subset

!conda run -n base pip install pytest

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/diffc
!conda run -n base python evaluate.py --config configs/SD-1.5-base.yaml --image_dir data/imagenet_subset --output_dir results/SD-1.5-base/imagenet_subset

import pandas as pd

csv_path = "/content/diffc/results/SD-1.5-base/imagenet_subset/results.csv"
df = pd.read_csv(csv_path)

# 1. Print a preview of the raw columns and data
print("--- CSV Data Preview ---")
print(f"Total rows generated: {len(df)}")
print("Columns in CSV:", df.columns.tolist())
print(df.head(3))

# 2. Identify the column used for the different quality steps
step_col = None
for col in df.columns:
    if any(k in col.lower() for k in ['step', 'time', 'recon_t', 'quality']) or col.lower() == 't':
        step_col = col
        break

# 3. Print the grouped Rate-Distortion averages
print("\n--- FINAL RATE-DISTORTION CURVE SUMMARY (Averages) ---")
if step_col:
    # Group by the timestep to show the average bpp, PSNR, MS-SSIM, and LPIPS per quality point
    summary = df.groupby(step_col).mean(numeric_only=True)
    # Sort from lowest step (highest compression) to highest step (highest quality)
    summary = summary.sort_index()
    print(summary)
else:
    print("Could not automatically group by step. Showing overall average across all runs:")
    print(df.mean(numeric_only=True))

import matplotlib.pyplot as plt
import pandas as pd

# Load the data and compute the grouped averages
csv_path = "/content/diffc/results/SD-1.5-base/imagenet_subset/results.csv"
df = pd.read_csv(csv_path)
summary = df.groupby('recon_timestep').mean(numeric_only=True).sort_index()

# Plotting setup
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

# Plot 1: bpp vs PSNR (Higher is better)
ax1.plot(summary['bpp'], summary['psnr'], marker='o', color='blue', linewidth=2)
ax1.set_title("Rate-Distortion Curve: PSNR (Higher is Better)")
ax1.set_xlabel("Bitrate (bpp)")
ax1.set_ylabel("PSNR (dB)")
ax1.grid(True, linestyle='--', alpha=0.6)

# Plot 2: bpp vs LPIPS (Lower is better)
ax2.plot(summary['bpp'], summary['lpips'], marker='s', color='red', linewidth=2)
ax2.set_title("Rate-Distortion Curve: LPIPS (Lower is Better)")
ax2.set_xlabel("Bitrate (bpp)")
ax2.set_ylabel("LPIPS Distortion")
ax2.grid(True, linestyle='--', alpha=0.6)

plt.tight_layout()
plt.savefig("/content/diffc/results/SD-1.5-base/imagenet_subset/rd_curves.png", dpi=300)
plt.show()

print("Plots generated and saved to: /content/diffc/results/SD-1.5-base/imagenet_subset/rd_curves.png")

import matplotlib.pyplot as plt
import os
from PIL import Image

# Select an image index to display (using 'img_0000.png' as a default)
image_filename = "img_0000.png"

gt_path = f"/content/diffc/data/imagenet_subset/{image_filename}"

# Map specific timesteps to their respective visual quality levels
recons = {
    "Original Ground Truth": gt_path,
    "Low Compression\n(0.136 bpp)": f"/content/diffc/results/SD-1.5-base/imagenet_subset/010/{image_filename}",
    "Medium Compression\n(0.018 bpp)": f"/content/diffc/results/SD-1.5-base/imagenet_subset/296/{image_filename}",
    "High Compression\n(0.0016 bpp)": f"/content/diffc/results/SD-1.5-base/imagenet_subset/897/{image_filename}"
}

fig, axes = plt.subplots(1, 4, figsize=(20, 6))

for i, (title, path) in enumerate(recons.items()):
    if os.path.exists(path):
        img = Image.open(path)
        axes[i].imshow(img)
        axes[i].set_title(title, fontsize=12, fontweight='bold')
        axes[i].axis('off')
    else:
        axes[i].text(0.5, 0.5, f"Image not found:\n{os.path.basename(path)}",
                     ha='center', va='center', color='red')
        axes[i].axis('off')

plt.tight_layout()
plt.savefig("/content/diffc/results/SD-1.5-base/imagenet_subset/visual_comparison.png", dpi=300)
plt.show()

print("Visual comparison grid saved to: /content/diffc/results/SD-1.5-base/imagenet_subset/visual_comparison.png")

import shutil

# 1. Compress the folder into a zip file
shutil.make_archive('diffcZ', 'zip', '/content/diffc')